"""
tessera_data.py
---------------
In silico observation sets.

No experimental time course exists that follows Cys38 occupancy, NF-kB
translocation, energy charge and survival simultaneously in one HT22
preparation, so the reference trajectories here are generated by the
calibrated model itself and corrupted with the measurement error typical of
the corresponding assay.  Every quantity reported in this work is therefore
an in silico result, and the comparisons that follow test recoverability,
identifiability and structural capability rather than agreement with
measurement.
"""

import numpy as np

import tessera_params as P
import tessera_model as M

# Sampling schedule a wet-lab protocol could realistically sustain (minutes).
SAMPLE_TIMES = np.array([0., 30., 60., 90., 120., 180., 240., 360., 480., 720.])

# Assay-specific multiplicative error, expressed as a coefficient of variation.
NOISE = dict(persulfide=0.18, sulfinate=0.22, nuclear=0.12,
             bclxl=0.16, atp=0.09, viability=0.07)

OBSERVABLES = ['persulfide', 'sulfinate', 'nuclear', 'bclxl', 'atp', 'viability']

# Panel used for parameter estimation.  Viability is excluded because it is
# a switch-like population quantity that the single-cell model cannot
# represent; it is held back as an independent population-level check.
FIT_PANEL = ['persulfide', 'sulfinate', 'nuclear', 'bclxl', 'atp']

# Panel available to a laboratory without site-resolved mass spectrometry.
FEASIBLE_PANEL = ['persulfide', 'nuclear', 'bclxl', 'atp']

# Panel available with imaging and a colorimetric assay only.
MINIMAL_PANEL = ['nuclear', 'atp']


def conditions():
    return [
        ("control",      dict(t_ogd=0.0)),
        ("ogd60",        dict(t_ogd=60.0)),
        ("ogd90",        dict(t_ogd=90.0)),
        ("ogd120",       dict(t_ogd=120.0)),
        ("ogd150",       dict(t_ogd=150.0)),
        ("ogd90_fast",   dict(t_ogd=90.0, donor_dose=150.0, donor_time=90.0,
                              donor_kind="bolus")),
        ("ogd90_slow",   dict(t_ogd=90.0, donor_dose=400.0, donor_time=0.0,
                              donor_kind="slow")),
    ]


def forward(p, barriers, gstate, cond_kw, variant="tessera", vpar=None,
            y0=None, times=None):
    times = SAMPLE_TIMES if times is None else times
    prot = M.Protocol(t_end=float(times[-1]), **cond_kw)
    if y0 is None:
        y0 = M.normoxic_steady_state(p, barriers, gstate, variant=variant,
                                     vpar=vpar)
    out = M.simulate(p=p, barriers=barriers, gstate=gstate, prot=prot,
                     t_eval=times, y0=y0, rtol=1e-6, atol=1e-9,
                     variant=variant, vpar=vpar)
    if out is None:
        return None
    t, Y = out
    return M.observables(t, Y, p)


def reference_dataset(seed=20260915, n_rep=3):
    """Generate the noisy in silico observation set used throughout."""
    rng = np.random.default_rng(seed)
    p, b, g = dict(P.NOMINAL), P.edge_barriers(), P.G_STATE.copy()
    y0 = M.normoxic_steady_state(p, b, g)
    data = {}
    truth = {}
    for name, kw in conditions():
        ob = forward(p, b, g, kw, y0=y0)
        truth[name] = {k: np.asarray(v, dtype=float) for k, v in ob.items()}
        rec = {}
        for key in OBSERVABLES:
            mu = np.maximum(np.asarray(ob[key], dtype=float), 1e-9)
            cv = NOISE[key]
            s = np.sqrt(np.log1p(cv ** 2))
            reps = mu[None, :] * np.exp(rng.normal(-0.5 * s * s, s,
                                                   size=(n_rep, mu.size)))
            rec[key] = reps
        data[name] = rec
    return dict(times=SAMPLE_TIMES, data=data, truth=truth, n_rep=n_rep)


def residuals(pred, obs, panel=None):
    """Standardised residuals on the log scale, matching the noise model."""
    panel = OBSERVABLES if panel is None else panel
    out = []
    for key in panel:
        cv = NOISE[key]
        s = np.sqrt(np.log1p(cv ** 2))
        mu = np.maximum(np.asarray(pred[key], dtype=float), 1e-9)
        y = np.maximum(obs[key], 1e-9)
        out.append(((np.log(y) - np.log(mu)) / s).ravel())
    return np.concatenate(out)
